CREATE TABLE record (
  	employee_id INT (9) NOT NULL,
  	user_pics varchar (50) NOT NULL,
  	username varchar (50) NOT NULL,
  	password varchar (50) NOT NULL,
  	role varchar (50) NOT NULL,
  	last_name VARCHAR (30) NOT NULL,
  	first_name VARCHAR (30) NOT NULL,
  	middle_name VARCHAR (30) NOT NULL,
  	department VARCHAR (30) NOT NULL,
  	date_employed date NOT NULL,
  	position VARCHAR (30) NOT NULL,
	leave_action VARCHAR (30) NOT NULL,
	leave_type VARCHAR (20) NOT NULL,
	leave_date_to date (20) NOT NULL,
	leave_date_from date (20) NOT NULL,
	filling_date date NOT NULL,
	approved_date_from  date NOT NULL,
	approved_date_to date NOT NULL,
	disapproved varchar (50) NOT NULL,
	sick_address varchar (50) NOT NULL,
	approved_for varchar (50) NOT NULL,
	vacation_address varchar (50) NOT NULL,
	vacation_specify varchar(50) NOT NULL,
	sick_specify varchar (50) NOT NULL,
	teaching_discipline INT (9) NOT NULL,
	prof_license INT (9) NOT NULL,
	tenure_employment INT (9) NOT NULL,
	faculty_rank INT (9) NOT NULL,
	teaching_load INT (9) NOT NULL,
	subjects_taught text (600) NOT NULL,
	month VARCHAR (10) NOT NULL,
	employment_status VARCHAR (20) NOT NULL,
  	employee_status VARCHAR (20) NOT NULL,
  	name_extension VARCHAR (5) NOT NULL,
  	birth_date DATE NOT NULL,
  	sex VARCHAR (20) NOT NULL,
  	civil_status VARCHAR (30) NOT NULL,
  	citizenship VARCHAR (30) NOT NULL,
  	height int (5) NOT NULL,
  	weight int (5) NOT NULL,
  	blood_type VARCHAR (10) NOT NULL,
  	gsis_no int (20) NOT NULL,
  	pagibig_no int (20) NOT NULL,
  	phil_health_no int (20) NOT NULL,
  	sss_no int (20) NOT NULL,
  	birth_place VARCHAR (80) NOT NULL,
  	residential_add VARCHAR (80) NOT NULL,
  	zip_code1 int (20) NOT NULL,
  	telephone_no1 int (20) NOT NULL,
	permanent_add VARCHAR (80) NOT NULL,
  	zip_code2 int (20) NOT NULL,
  	telephone_no2 int (20) NOT NULL,
  	email_address VARCHAR (50) NOT NULL,
  	cellphone_no VARCHAR (50) NOT NULL,
  	agency_employee_no int (20) NOT NULL,
  	tin int (20) NOT NULL,
  	spouse_last_name VARCHAR (30) NOT NULL,
  	spouse_first_name VARCHAR (30) NOT NULL,
  	spouse_middle_name VARCHAR (30) NOT NULL,
  	occupation VARCHAR (30) NOT NULL,
  	employer_bus_name VARCHAR (50) NOT NULL,
  	business_address VARCHAR (80) NOT NULL,
  	spouse_cp_no int (20) NOT NULL,
  	spouse_birth_date date NOT NULL,
  	child_name1 VARCHAR (30) NOT NULL,
  	child_birth_date1 date NOT NULL,
	child_name2 VARCHAR (30) NOT NULL,
  	child_birth_date2 date NOT NULL,
	child_name3 VARCHAR (30) NOT NULL,
  	child_birth_date3 date NOT NULL,
	child_name4 VARCHAR (30) NOT NULL,
  	child_birth_date4 date NOT NULL,
	child_name5 VARCHAR (30) NOT NULL,
  	child_birth_date5 date NOT NULL,
	child_name6 VARCHAR (30) NOT NULL,
  	child_birth_date6 date NOT NULL,
	child_name7 VARCHAR (30) NOT NULL,
  	child_birth_date7 date NOT NULL,
	child_name8 VARCHAR (30) NOT NULL,
  	child_birth_date8 date NOT NULL,
	child_name9 VARCHAR (30) NOT NULL,
  	child_birth_date9 date NOT NULL,
	child_name10 VARCHAR (30) NOT NULL,
  	child_birth_date10 date NOT NULL,
  	father_last_name VARCHAR (30) NOT NULL,
  	father_first_name VARCHAR (30) NOT NULL,
  	father_middle_name VARCHAR (30) NOT NULL,
  	father_birth_date date NOT NULL,
  	mother_maiden_name VARCHAR (30) NOT NULL,
  	mother_last_name VARCHAR (30) NOT NULL,
  	mother_first_name VARCHAR (30) NOT NULL,
  	mother_middle_name VARCHAR (30) NOT NULL,
  	mother_birth_date date NOT NULL,
  	primary_name VARCHAR (50) NOT NULL,
    primary_deg_course VARCHAR (50) NOT NULL,
  	primary_year_grad int (5) NOT NULL,
  	primary_highest_grade int (3) NOT NULL,
	primary_attendance_from int (9) NOT NULL,
	primary_attendance_to int (9) NOT NULL,
  	primary_academic VARCHAR (50) NOT NULL,
  	secondary_name VARCHAR (50) NOT NULL,
    secondary_deg_course VARCHAR (50) NOT NULL,
  	secondary_year_grad int (5) NOT NULL,
  	secondary_highest_grade int (3) NOT NULL,
	secondary_attendance_from int (9) NOT NULL,
	secondary_attendance_to int (9) NOT NULL,
  	secondary_academic VARCHAR (50) NOT NULL,
  	college_name VARCHAR (50) NOT NULL,
    college_deg_course VARCHAR (50) NOT NULL,
  	college_year_grad int (5) NOT NULL,
  	college_highest_grade int (3) NOT NULL,
	college_attendance_from int (9) NOT NULL,
	college_attendance_to int (9) NOT NULL,
  	college_academic VARCHAR (50) NOT NULL,
  	grad_studies_name VARCHAR (50) NOT NULL,
    grad_deg_course VARCHAR (50) NOT NULL,
    grad_studies_year int (5) NOT NULL,
  	grad_studies_highest_grade int (3) NOT NULL,
	grad_attendance_from int (9) NOT NULL,
	grad_attendance_to int (9) NOT NULL,
  	grad_studies_academic VARCHAR (50) NOT NULL,
	grad_studies_name1 VARCHAR (50) NOT NULL,
    grad_deg_course1 VARCHAR (50) NOT NULL,
    grad_studies_year1 int (5) NOT NULL,
  	grad_studies_highest_grade1 int (3) NOT NULL,
	grad_attendance_from1 int (9) NOT NULL,
	grad_attendance_to1 int (9) NOT NULL,
  	grad_studies_academic1 VARCHAR (50) NOT NULL,
  	primary key(employee_id))